-- Creating table to receive values 

CREATE TABLE industrialized_meds00 (
    ANO_VENDA INT,
    MES_VENDA INT,
    UF_VENDA VARCHAR(2),
    MUNICIPIO_VENDA VARCHAR(100),
    PRINCIPIO_ATIVO VARCHAR(100),
    DESCRICAO_APRESENTACAO VARCHAR(100),
    QTD_VENDIDA INT,
    UNIDADE_MEDIDA VARCHAR(20),
    CONSELHO_PRESCRITOR VARCHAR(50),
    UF_CONSELHO_PRESCRITOR VARCHAR(2),
    TIPO_RECEITUARIO FLOAT,
    CID10 VARCHAR(10),
    SEXO FLOAT,
    IDADE FLOAT,
    UNIDADE_IDADE FLOAT
);
